export default {
  LOAD_NEWS: 'LOAD_NEWS',
  LOAD_NEWS_FAILURE: 'LOAD_NEWS_FAILURE',
  LOAD_NEWS_SUCCESS: 'LOAD_NEWS_SUCCESS',

  LOAD_USERS: 'LOAD_USERS',
  LOAD_USERS_FAILURE: 'LOAD_USERS_FAILURE',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',

  LOAD_WEEK_PREF: 'LOAD_WEEK_PREF',
  LOAD_WEEK_PREF_FAILURE: 'LOAD_WEEK_PREF_FAILURE',
  LOAD_WEEK_PREF_SUCCESS: 'LOAD_WEEK_PREF_SUCCESS',

  LOAD_SUMMARY: 'LOAD_SUMMARY',
  LOAD_SUMMARY_FAILURE: 'LOAD_SUMMARY_FAILURE',
  LOAD_SUMMARY_SUCCESS: 'LOAD_SUMMARY_SUCCESS',

  NAVIGATE: 'NAVIGATE',

  UPDATE_USER: 'UPDATE_USER',

  SELECT_USER: 'SELECT_USER',

  SUBMIT_WEEK_PREF: 'SUBMIT_WEEK_PREF',

  HIDE_PROFILE_SWITCHER: 'HIDE_PROFILE_SWITCHER',
  SHOW_PROFILE_SWITCHER: 'SHOW_PROFILE_SWITCHER',

  HIDE_WHATS_NEW: 'HIDE_WHATS_NEW',
  SHOW_WHATS_NEW: 'SHOW_WHATS_NEW',

  MARK_NEWS_ITEM_READ: 'MARK_NEWS_ITEM_READ',

  DISPLAY_TOAST: 'DISPLAY_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  SHOW_TOAST: 'SHOW_TOAST',

  LOAD_CURRENT_USER: 'LOAD_CURRENT_USER',
  SWITCH_CURRENT_USER: 'SWITCH_CURRENT_USER',

  TOGGLE_DAY: 'TOGGLE_DAY',
};
