export default {
  LOAD_USERS: 'LOAD_USERS',
  LOAD_USERS_FAILURE: 'LOAD_USERS_FAILURE',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',

  LOAD_WEEK_PREF: 'LOAD_WEEK_PREF',
  LOAD_WEEK_PREF_FAILURE: 'LOAD_WEEK_PREF_FAILURE',
  LOAD_WEEK_PREF_SUCCESS: 'LOAD_WEEK_PREF_SUCCESS',

  SELECT_USER: 'SELECT_USER',

  SUBMIT_WEEK_PREF: 'SUBMIT_WEEK_PREF',
  SUBMIT_WEEK_PREF_FAILURE: 'SUBMIT_WEEK_PREF_FAILURE',
  SUBMIT_WEEK_PREF_SUCCESS: 'SUBMIT_WEEK_PREF_SUCCESS',

  HIDE_PROFILE_SWITCHER: 'HIDE_PROFILE_SWITCHER',
  SHOW_PROFILE_SWITCHER: 'SHOW_PROFILE_SWITCHER',

  LOAD_CURRENT_USER: 'LOAD_CURRENT_USER',
  SWITCH_CURRENT_USER: 'SWITCH_CURRENT_USER',

  TOGGLE_DAY: 'TOGGLE_DAY',
};
