export default {
  LOAD_USERS: 'LOAD_USERS',
  LOAD_USERS_FAILURE: 'LOAD_USERS_FAILURE',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',

  SELECT_USER: 'SELECT_USER',

  HIDE_PROFILE_SWITCHER: 'HIDE_PROFILE_SWITCHER',
  SHOW_PROFILE_SWITCHER: 'SHOW_PROFILE_SWITCHER',

  SWITCH_CURRENT_USER: 'SWITCH_CURRENT_USER',

  TOGGLE_DAY: 'TOGGLE_DAY',
};
